//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emr.API
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TripFriendsDBEntities : DbContext
    {
        public TripFriendsDBEntities()
            : base("name=TripFriendsDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<UsersData> UsersDatas { get; set; }
        public virtual DbSet<TripsData> TripsDatas { get; set; }
        public virtual DbSet<FeedbacksData> FeedbacksDatas { get; set; }
    }
}
